[workspace]
members = [
  "hcctl",
  "healthchecks",
  "monitor",
]

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"

[workspace.dependencies]
clap = { version = "4.1.11", features = [ "color", "deprecated", "derive" ] }
