allow-branch = ["main"]
consolidate-pushes = true
dependent-version = "upgrade"
sign-commit = true
sign-tag = true
push = true
pre-release-commit-message = "chore(release): bump {{crate_name}} to version {{version}}"
post-release-commit-message = "chore(release): start next development iteration {{crate_name}}-{{version}}"
