allow-branch = ["main"]
push = true
consolidate-commits = false
pre-release-commit-message = "chore(release): bump {{crate_name}} to version {{version}}"
sign-commit = false
sign-tag = false
tag-message = "{{crate_name}} version {{version}}"
